# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=200)),
                ('queued_time', models.DateTimeField()),
                ('place_in_line', models.IntegerField()),
            ],
        ),
    ]
