# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='queued_time',
            field=models.DateTimeField(verbose_name='time queued'),
        ),
    ]
