# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partyqueue', '0002_auto_20160706_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='queued_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
