# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyqueue', '0003_queueitem_queued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='queued_by',
            field=models.IntegerField(blank=True),
        ),
    ]
