# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyqueue', '0005_auto_20160711_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueitem',
            name='queued_by',
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='place_in_line',
            field=models.IntegerField(),
        ),
    ]
