# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyqueue', '0006_auto_20160711_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='queued_by',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='place_in_line',
            field=models.IntegerField(blank=True),
        ),
    ]
